language: node_js

node_js:
  - '0.11'
  - '0.10'

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_script:
  - npm i coveralls@2.11 codeclimate-test-reporter@0.0.4
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js